### ISSUE TITLE
Generalized linear model - fit4

### ISSUE THREAD

**Issue by spangster** [bstaton1/au-r-workshop#17]
When I go to create fit4 from the glm section, I don't get the same results as in the book. Instead I get 2 linear plots, with different slopes. However, if I add family = "binomial" to the code for fit3, I do get the plot and AIC values that the book associated with fit4.

fit4 = glm(binary ~ type * weight, data = dat) #doesnt work
![fit4](https://user-images.githubusercontent.com/35468105/51649826-fb472080-1f53-11e9-9f77-0f4046a44732.png)

fit4 = glm(binary ~ type + weight, data = dat, family = "binomial") #works
![fit3 with family binomial](https://user-images.githubusercontent.com/35468105/51649879-203b9380-1f54-11e9-9f70-38a436d4a013.png)

**Comment by bstaton1** [comment]
Hello, and thank you for sharing this!

This is a glaring typo that I'm very surprised made it through our review. You are correct in that the `family = "binomial"` (`family = binomial`) also works) argument **must** be specified if you want to fit a logistic regression using `glm()`. Without specifying the family, `glm()` will use the normal distribution for errors and the identity function for the link function (i.e., a standard linear model). The correct syntax for the four models in the GLM section is:

```
fit1 = glm(binary ~ weight, data = dat, family = "binomial")
fit2 = glm(binary ~ type, data = dat, family = "binomial")
fit3 = glm(binary ~ type + weight, data = dat, family = "binomial")
fit4 = glm(binary ~ type * weight, data = dat, family = "binomial")
```

The rest of the code is correct, but this plot is incorrect as published:

![image](https://user-images.githubusercontent.com/42722538/51691507-83630f80-1fc0-11e9-85fa-c1e6d91a3bc9.png)

The AIC table and inference about the best model are also almost certainly wrong as currently published. 

I have a running list of typos/things to address for when I'm able to sit down with this again and improve it. This typo is the most significant of any identified so far so it's going on the top of the list! I'll keep the issue open until I fix this.

Please feel free to share any more issues you find, and thanks again!
