### ISSUE TITLE
google maps error

### ISSUE THREAD

**Issue by bstaton1** [bstaton1/au-r-workshop#4]
@henryjhershey :

I think it would be nice to include some brief examples of `{ggmap}` and `{leaflet}` packages. Just show a code block and the output - no tutorial.

When I try to make a map with `{ggmap}` using a basic online example:
```
library(ggmap)
geocode("United States")
qmap(location = "boston university")
```
I get an error message: 

`Information from URL : http://maps.googleapis.com/maps/api/geocode/json address=United%20States&sensor=false
geocode failed with status OVER_QUERY_LIMIT, location = "United States"  lon lat`

Coincidentally, I got a similar 403 Forbidden message from `gmap()` in your code. Any idea what's up here??

`leaflet()` works fine (but won't render in PDF obviously). Here's what I've got so far:

```
library(leaflet)
leaflet() %>%
  addProviderTiles(providers$Esri.WorldGrayCanvas, group = "Grey") %>%
  fitBounds(slovenia@bbox["x","min"], slovenia@bbox["y","min"],
            slovenia@bbox["x","max"], slovenia@bbox["y","max"]) %>%
  addPolygons(data = slovenia, color = "red") %>%
  addCircles(~x, ~y, data = bear) %>%
  addPolylines(data = railways,opacity = 1, color = "grey")
```

I haven't pushed these changes to github yet.

**Comment by henryjhershey** [comment]
I have no idea why that error happens. it happens every other time I run the code, but not every time. Maybe has something to do with API keys? https://developers.google.com/maps/documentation/geocoding/get-api-key

**Comment by bstaton1** [comment]
We still don't have this figured out, but we can get around it by creating a png on a separate computer, saving it to the repo, then putting it in the content using `knitr::include_graphics()`.
